import type { Metadata } from "next";
import ClientLayout from "./ClientLayout";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { GtfsDataLoader } from "./GtfsDataLoader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Load the data on server side
  await GtfsDataLoader();

  return (
    <html lang="en">
      <ClientLayout>{children}</ClientLayout>
      <SpeedInsights />
    </html>
  );
}
