import type { Metadata } from "next";
import ClientLayout from "./ClientLayout";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarProvider } from "@/components/ui/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Load the data on server side

  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <ClientLayout>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider defaultOpen={false}>{children}</SidebarProvider>
        </ThemeProvider>
      </ClientLayout>
      <SpeedInsights />
    </html>
  );
}
